# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubeport" do
  name "kubeport"
  desc "Kubernetes port-forward supervisor with health checks and auto-restart"
  homepage "https://github.com/rbaliyan/kubeport"
  version "0.4.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubeport"

  on_macos do
    on_intel do
      url "https://github.com/rbaliyan/kubeport/releases/download/v#{version}/kubeport_#{version}_darwin_amd64.tar.gz"
      sha256 "60963ae41478a209f2691608b1ea69ed47d3e06cddc59f25a9a1bd15a3e146a2"
    end
    on_arm do
      url "https://github.com/rbaliyan/kubeport/releases/download/v#{version}/kubeport_#{version}_darwin_arm64.tar.gz"
      sha256 "407a31927162659078751815f2a68be86dac45272ca5d2853a6f1a33ccd4d907"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rbaliyan/kubeport/releases/download/v#{version}/kubeport_#{version}_linux_amd64.tar.gz"
      sha256 "4ac2fbf081dfa9c4efcb07af487b155b45434cc33f2958819398f47501934660"
    end
    on_arm do
      url "https://github.com/rbaliyan/kubeport/releases/download/v#{version}/kubeport_#{version}_linux_arm64.tar.gz"
      sha256 "b2d72dafd48005dce58c0af99283b878527dde31bd65fc050e398bb6ae661d30"
    end
  end

  # No zap stanza required
end
