# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeport < Formula
  desc "Kubernetes port-forward supervisor with health checks and auto-restart"
  homepage "https://github.com/rbaliyan/kubeport"
  version "0.6.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rbaliyan/kubeport/releases/download/v0.6.5/kubeport_0.6.5_darwin_amd64.tar.gz"
      sha256 "444b05303ccf9d8a06cded41fc984b491c003f33954cdc10db5013a2f2e8ea20"

      define_method(:install) do
        bin.install "kubeport"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rbaliyan/kubeport/releases/download/v0.6.5/kubeport_0.6.5_darwin_arm64.tar.gz"
      sha256 "cc55b0119624bf24b7161f23711c74158f635d4b9a2847d104a7e60b105f7cc8"

      define_method(:install) do
        bin.install "kubeport"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rbaliyan/kubeport/releases/download/v0.6.5/kubeport_0.6.5_linux_amd64.tar.gz"
      sha256 "0b48b8c40b8114ef0e061768991702f5998cf1e583dd2ae8cb474a59a07015a6"
      define_method(:install) do
        bin.install "kubeport"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rbaliyan/kubeport/releases/download/v0.6.5/kubeport_0.6.5_linux_arm64.tar.gz"
      sha256 "324d1e6b445827fde2028e568b9edee224d0a87507467d867aa4116e97ace51a"
      define_method(:install) do
        bin.install "kubeport"
      end
    end
  end

  test do
    system "#{bin}/kubeport", "version"
  end
end
