# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ledger < Formula
  desc "Append-only log daemon with gRPC API and pluggable storage backends"
  homepage "https://github.com/rbaliyan/ledger"
  version "0.0.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rbaliyan/ledger/releases/download/v0.0.11/ledger_0.0.11_darwin_amd64.tar.gz"
      sha256 "119217b03ae8d5ae58f4cd0f8f4528a8f569e5ec22e5651733bba2ef3e4cdf1e"

      define_method(:install) do
        bin.install "ledger"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rbaliyan/ledger/releases/download/v0.0.11/ledger_0.0.11_darwin_arm64.tar.gz"
      sha256 "a809fdd2e45800c6cae4ea185642687c433da99e8c96dc7c7096515beb32532d"

      define_method(:install) do
        bin.install "ledger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rbaliyan/ledger/releases/download/v0.0.11/ledger_0.0.11_linux_amd64.tar.gz"
      sha256 "e83cfaf711b1b5e33628d630454eb25c31745620f783e508175ec4154140c2b5"
      define_method(:install) do
        bin.install "ledger"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rbaliyan/ledger/releases/download/v0.0.11/ledger_0.0.11_linux_arm64.tar.gz"
      sha256 "f93c9aa792fdaa4f9a6b675eab486b76b27b424b70808a9a11d713b6e7a15447"
      define_method(:install) do
        bin.install "ledger"
      end
    end
  end

  test do
    system "#{bin}/ledger", "version"
  end
end
