# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ledger < Formula
  desc "Append-only log daemon with gRPC API and pluggable storage backends"
  homepage "https://github.com/rbaliyan/ledger"
  version "0.0.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rbaliyan/ledger/releases/download/v0.0.12/ledger_0.0.12_darwin_amd64.tar.gz"
      sha256 "ba92436ea91b15dba881bf4d3fc3d36910f87ff4af76e6c5836652bf1551ace2"

      define_method(:install) do
        bin.install "ledger"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rbaliyan/ledger/releases/download/v0.0.12/ledger_0.0.12_darwin_arm64.tar.gz"
      sha256 "cb7bb55f6201e31f8aba228ce9795bb710af8e759bdce71fb54da2366bfca350"

      define_method(:install) do
        bin.install "ledger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rbaliyan/ledger/releases/download/v0.0.12/ledger_0.0.12_linux_amd64.tar.gz"
      sha256 "d5f96d23fe2601adb0b6c1e0dca9aed7764342e3406f4fae21c38c376a6ec714"
      define_method(:install) do
        bin.install "ledger"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rbaliyan/ledger/releases/download/v0.0.12/ledger_0.0.12_linux_arm64.tar.gz"
      sha256 "72f6ae2807e21d207072778873af25461d8ccaeb35316ecd6f9314881e935695"
      define_method(:install) do
        bin.install "ledger"
      end
    end
  end

  test do
    system "#{bin}/ledger", "version"
  end
end
