# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ledger < Formula
  desc "Append-only log daemon with gRPC API and pluggable storage backends"
  homepage "https://github.com/rbaliyan/ledger"
  version "0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rbaliyan/ledger/releases/download/v0.0.9/ledger_0.0.9_darwin_amd64.tar.gz"
      sha256 "dcdde93d74f47a5f664da6958b1b21cec34298c5b8abf3e9ec67e98093043082"

      define_method(:install) do
        bin.install "ledger"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rbaliyan/ledger/releases/download/v0.0.9/ledger_0.0.9_darwin_arm64.tar.gz"
      sha256 "d0086c446576fc7aee829b586d6f17a59d48ce5e6233b291b802dcfb2310bce8"

      define_method(:install) do
        bin.install "ledger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rbaliyan/ledger/releases/download/v0.0.9/ledger_0.0.9_linux_amd64.tar.gz"
      sha256 "3f764dc97f8dac492bbeefbfb55f6c82f1d1cb600c0598291ce9534b29296213"
      define_method(:install) do
        bin.install "ledger"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rbaliyan/ledger/releases/download/v0.0.9/ledger_0.0.9_linux_arm64.tar.gz"
      sha256 "b003198fbbf31967e9cccd7d102bc4736117e708ccc916ccaebb5a21391c1a18"
      define_method(:install) do
        bin.install "ledger"
      end
    end
  end

  test do
    system "#{bin}/ledger", "version"
  end
end
